In [1]:
import numpy as np

In [2]:
a=np.ones((7,7))

In [3]:
y,x = np.ogrid[-3: 3+1, -3: 3+1]
mask = x**2+y**2 <= 3**2

In [4]:
mask

array([[False, False, False,  True, False, False, False],
       [False,  True,  True,  True,  True,  True, False],
       [False,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True, False],
       [False,  True,  True,  True,  True,  True, False],
       [False, False, False,  True, False, False, False]], dtype=bool)

In [5]:
a[mask]=0

In [6]:
list(a)


[array([ 1.,  1.,  1.,  0.,  1.,  1.,  1.]),
 array([ 1.,  0.,  0.,  0.,  0.,  0.,  1.]),
 array([ 1.,  0.,  0.,  0.,  0.,  0.,  1.]),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.]),
 array([ 1.,  0.,  0.,  0.,  0.,  0.,  1.]),
 array([ 1.,  0.,  0.,  0.,  0.,  0.,  1.]),
 array([ 1.,  1.,  1.,  0.,  1.,  1.,  1.])]

In [17]:
import numpy as np

a, b = 45, 49
n = 86
r = 18

y,x = np.ogrid[-a:n-a, -b:n-b]
mask = x*x + y*y <= r*r

array = np.ones((n, n))
array[mask] = 255

In [18]:
list(array)

[array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]),
 array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]),
 array([ 1.,  1.,  1.,  

In [19]:
#write the coordinates to a text file

In [20]:
where=np.where (mask == 1)

In [21]:
print (where)

(array([27, 28, 28, ..., 62, 62, 63], dtype=int64), array([49, 44, 45, ..., 53, 54, 49], dtype=int64))


In [22]:
len(where[1])

1009

In [23]:
myfile = open('output1.inp', 'a')
for x, y in zip(where[0], where[1]):
    print(s.substitute(xxxx='{:03d}'.format(x), yyyy='{:03d}'.format(y)), file=myfile)
myfile.close()

In [8]:
from string import Template
s=Template(open ('circle_start.inp').read())

In [15]:
s

In [32]:
myfile = open('output.inp', 'w')
print(s.substitute(xxxx='10', yyyy = '10'), file=myfile)
myfile.close()

In [33]:
!cat output.inp

'cat' is not recognized as an internal or external command,
operable program or batch file.
